[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust"

create-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.cpython]
version = "*"
features = ["extension-module"]
