[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust"
crate-type = ["cdylib"]

[dependencies]
cpython = { version = "0.7.1", features = ["extension-module"] }
rand = { version = "0.8.5", features = ["small_rng"] }
rand_chacha = "0.3.1"
