class PyCube2x2:
    observation_length: int
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def is_solved(self) -> bool: ...
    def get_observations(self) -> list[int]: ...
    def apply_action(self, action: int) -> None: ...
    def scramble(self, action: int) -> int: ...
    def scramble_with_seed(self, seed: int, steps: int) -> None: ...

class PyCube3x3:
    observation_length: int
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def is_solved(self) -> bool: ...
    def get_observations(self) -> list[int]: ...
    def apply_action(self, action: int) -> None: ...
    def scramble(self, action: int) -> int: ...
    def scramble_with_seed(self, seed: int, steps: int) -> None: ...
