name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_test:
    name: Test Rust Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/cache@v3
        name: Rust Cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-rust-cargo-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-cargo-
      - uses: actions/cache@v3
        name: Rust Target Cache
        with:
          path: |
            rust/target/
          key: ${{ runner.os }}-rust-target-${{ hashFiles('rust/Cargo.lock') }}-${{ hashFiles('rust/**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-rust-target-${{ hashFiles('rust/Cargo.lock') }}-
            ${{ runner.os }}-rust-target-
      - name: Run Tests
        run: cd rust && cargo test
  rust_python_test:
    name: Test Rust Python Module
    needs: [rust_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.9
          activate-conda: true
      - uses: actions/cache@v3
        name: Rust Cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-rust-cargo-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-cargo-
      - uses: actions/cache@v3
        name: Rust Target Cache
        with:
          path: |
            rust/target/
          key: ${{ runner.os }}-rust-target-${{ hashFiles('rust/Cargo.lock') }}-${{ hashFiles('rust/**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-rust-target-${{ hashFiles('rust/Cargo.lock') }}-
            ${{ runner.os }}-rust-target-
      - uses: actions/cache@v3
        name: Rust Pytest Cache
        with:
          path: |
            rust/.pytest_cache/
            rust/pytest/__pycache__/
          key: ${{runner.os}}-rust-pytest-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('rust/pytest/*.py') }}
          restore-keys: |
            ${{ runner.os }}-rust-pytest-${{ hashFiles('**/requirements.txt') }}-
            ${{ runner.os }}-rust-pytest-
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: Build Rust Release
        run: cd rust && maturin develop
      - name: Run Python Tests
        run: cd rust && pytest
  api_test:
    name: Test Rust API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/cache@v3
        name: Rust Cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-api-cargo-${{ hashFiles('api/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-api-cargo-
      - uses: actions/cache@v3
        name: Rust Target Cache
        with:
          path: |
            rust/target/
          key: ${{ runner.os }}-api-target-${{ hashFiles('api/Cargo.lock') }}-${{ hashFiles('api/**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-api-target-${{ hashFiles('api/Cargo.lock') }}-
            ${{ runner.os }}-api-target-
      - name: Run Tests
        run: cd api && cargo test
