name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_test:
    name: Test Rust Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Run Tests
        run: cd rust && cargo test
  rust_python_test:
    name: Test Rust Python Module
    needs: [rust_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.9
          activate-conda: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - uses: actions/cache@v3
        name: Rust Pytest Cache
        with:
          path: |
            rust/.pytest_cache/
            rust/pytest/__pycache__/
          key: ${{runner.os}}-rust-pytest-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('rust/pytest/*.py') }}
          restore-keys: |
            ${{ runner.os }}-rust-pytest-${{ hashFiles('**/requirements.txt') }}-
            ${{ runner.os }}-rust-pytest-
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: Build Rust Release
        run: cd rust && maturin develop
      - name: Run Python Tests
        run: cd rust && pytest
