name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_build:
    name: Build Rust Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/cache@v3
        name: Rust Cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-rust-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-cargo-
      - uses: actions/cache@v3
        name: Rust Target Cache
        with:
          path: |
            rust/target/
          key: ${{ runner.os }}-rust-target-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('rust/**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-rust-target-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-rust-target-
      - name: Run Tests
        run: cd rust && cargo test --verbose
      - name: Build Maturin
        run: cd rust && maturin develop
  rust_python_test:
    name: Test Rust Python Module
    needs: [rust_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: actions/cache@v3
        name: Rust Cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-rust-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-cargo-
      - uses: actions/cache@v3
        name: Rust Target Cache
        with:
          path: |
            rust/target/
          key: ${{ runner.os }}-rust-target-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('rust/**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-rust-target-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-rust-target-
      - uses: actions/cache@v3
        name: Rust Pytest Cache
        with:
          path: |
            rust/.pytest_cache/
            rust/python/__pycache__/
          key: ${{runner.os}}-rust-pytest-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('rust/**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-rust-pytest-${{ hashFiles('**/requirements.txt') }}-
            ${{ runner.os }}-rust-pytest-
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: Build Rust Release
        run: cd rust && maturin develop
      - name: Run Python Tests
        run: cd rust && pytest
